### ChatGPT
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "I want you to act as a Java developer."
    },
    {
      "role": "user",
      "content": "Could you introduce Google Guava?"
    }
  ]
}

### ChatGPT transplate
POST https://api.openai.com/v1/chat/completions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "model": "gpt-3.5-turbo",
  "messages": [
    {
      "role": "system",
      "content": "I want you to act as an English to Chinese translator."
    },
    {
      "role": "user",
      "content": "Hello, how are you?"
    }
  ]
}